
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import code
import glob
from itertools import count
from pathlib import Path
import random
from pygame import mixer
import wave

from textwrap import fill

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

#======================================================================================================#
#GUIDE TO RUN THIS CODE

#[1]Change directory where "Final_PIT" folder is located 
#[2]Double the slash
#Ex: Build_Location = C:\\Users\\ROGER\\Desktop\\Final_PIT\\

Final_PIT_Location = "C:\\Users\\ROGER\\source\\repos\\Final_PIT\\"

#INSTALL in TERMINAL
#   pip install pygame

#######################################################################################################

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(f"{Final_PIT_Location}//assets//frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x700")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 700,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

####################################################################################################

_toGuess = (random.randrange(1,10))
_guess = 0
_money = 10000
_bet = 0
_status = ""
_removing = False
_show = False

####################################################################################################
#colors

#red = #FD0000
#green = #6FFD00


####################################################################################################

Guess_comments = ["Are you Sure?","GoodLuck on \nthat number","No, \nnot that number"]
Bet_comments = ["Place More Bet!","That Money \nwill be Mine", "\nDon't Regret it Later","\nMore! MOre! MOre!"]
not_Enough_MOney = ["You Slap Soil!","Bum!","How Poor! :(","No Beggar!"]

####################################################################################################

class _music:
    
    def __init__(self,file_path, channel):
        try:
            wave_file = wave.open(file_path, 'rb')
            mixer.init(frequency=wave_file.getframerate())
            mixer.Channel(channel).play(mixer.Sound(file_path))
        except Exception as e:
            print(f"Error: {e}")

def startUP():
    global _toGuess
    
    _toGuess = (random.randrange(1,10))

def remove_button():
    global _removing
    global _show
    button_fx = _music(f"{Final_PIT_Location}//assets//Button_fx.wav",1)
    if _show == False:
        if _removing == False:
           _removing = True
       
           _status = "REMOVING BET!"
           canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
           canvas.itemconfig(tagOrId=txt_bet, fill="#FD0000")
           return       
        elif _removing == True:
            _removing = False
            _status = "ADD BET!"
            canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#6FFD00")
            canvas.itemconfig(tagOrId=txt_bet, fill="#6FFD00")
            return               
    else:
        _status = "Press Enter..."
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
        error_fx = _music(f"{Final_PIT_Location}//assets//Error2.wav",1)
    
def bet_button(_chip):
    global _money
    global _bet
    global _status
    
    button_fx = _music(f"{Final_PIT_Location}//assets//Button_fx4.wav",1)
    
    #remover process
    if _removing == True:
      
        _status = f"+{_chip}"
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#6FFD00")
        canvas.itemconfig(tagOrId=txt_bet, fill="#FD0000")
        if _bet < _chip:

            _status = "Not Enough\nBet Money!"
            canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
            canvas.itemconfig(tagOrId=txt_money, text=f"${_money}", fill=f"white")
            error_fx = _music(f"{Final_PIT_Location}//assets//Error2.wav",1)
            return
    
        _money += _chip
        _bet -= _chip
        
        
        canvas.itemconfig(tagOrId=txt_money, text=f"${_money}", fill=f"#6FFD00")
        canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}")
####################################################################################################
#betting process

    if _removing == False:
        
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="white")
        canvas.itemconfig(tagOrId=txt_guess, fill="white")
        if _show == False:         

            if _chip > _money:
            
                _status =  _status = f"Com:{random.choice(not_Enough_MOney)}"
                canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
                canvas.itemconfig(tagOrId=txt_money, text=f"${_money}", fill="#FD0000")
                error_fx = _music(f"{Final_PIT_Location}//assets//Error2.wav",1)
                return
        
            _money -= _chip
            _bet += _chip
        

            _status = f"Com:{random.choice(Bet_comments)}"
            canvas.itemconfig(tagOrId=txt_money, text=f"${_money}", fill=f"#FD0000")
            canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}", fill="#6FFD00")
         
        else:
            _status = "Press Enter..."
            canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
            canvas.itemconfig(tagOrId=txt_money,fill="white")
            canvas.itemconfig(tagOrId=txt_bet,fill="white")
            error_fx = _music(f"{Final_PIT_Location}//assets//Error.wav",1)
                               
def guess_button(_userGuess):
        global _guess
        global _status
        global Guess_comments
        global _show
        
        button_fx = _music(f"{Final_PIT_Location}//assets//Button_fx3.wav",1)
        
        if _show == False:
            _guess = _userGuess
            _status = f"Com:{random.choice(Guess_comments)}"
            canvas.itemconfig(tagOrId=txt_guess, text=f"{_guess}", fill="#6FFD00")
            canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}", fill="white")
            canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="white")
            canvas.itemconfig(tagOrId=txt_money,fill="white")
        else:
            _status = "Press Enter..."
            canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
            canvas.itemconfig(tagOrId=txt_money,fill="white")
            canvas.itemconfig(tagOrId=txt_bet,fill="white")
            error_fx = _music(f"{Final_PIT_Location}//assets//Error.wav",1)
            
def enter_button():
    global _guess
    global _toGuess
    global _bet
    global _money
    global _status
    global _show
    
    startUP()
    button_fx = _music(f"{Final_PIT_Location}//assets//Button_fx.wav",1)
    
    if _show == True:

        _status = "RESET"
        _guess = 0
        _toGuess = 0
        
        canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}", fill="White")
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="White")
        canvas.itemconfig(tagOrId=txt_guess, text=f"{_guess}", fill="White")
        canvas.itemconfig(tagOrId=txt_toGuess, text=f"{_toGuess}", fill="White")
        
        _show = False
        return
        
    if _bet == 0:
        _status = "No Bet Detected!"
        canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}", fill="#FD0000")
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
        error_fx = _music(f"{Final_PIT_Location}//assets//Error.wav",1)
        
        return
    
    if _guess == 0:
        _status = "No Guess number \nDetected!"
        canvas.itemconfig(tagOrId=txt_guess, fill="#FD0000")
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FD0000")
        canvas.itemconfig(tagOrId=txt_money,fill="white")
        canvas.itemconfig(tagOrId=txt_bet,fill="white")
        error_fx = _music(f"{Final_PIT_Location}//assets//Error.wav",1)

        return
    
    if _guess == _toGuess:
        
        _money += _bet*2
        
        _status = f"You WIN! ${_bet*2}"
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}", fill="#FFD600")
        canvas.itemconfig(tagOrId=txt_toGuess, text=f"{_toGuess}")
        canvas.itemconfig(tagOrId=txt_money, text=f"${_money}",fill="#FFD600")
        canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}")
        

        event_fx = _music(f"{Final_PIT_Location}//assets//Win_coin.wav",2)
        
        _show = True
        
    else:

        _status = f"You LOSE! ${_bet}"
        canvas.itemconfig(tagOrId=txt_status, text=f"{_status}",fill="#FD0000")
        canvas.itemconfig(tagOrId=txt_toGuess, text=f"{_toGuess}")
        
        event_fx = _music(f"{Final_PIT_Location}//assets//SAD.wav",2)
        
        _bet = 0
        
        canvas.itemconfig(tagOrId=txt_guess,fill="#FD0000")
        canvas.itemconfig(tagOrId=txt_money, text=f"${_money}", fill="white")
        canvas.itemconfig(tagOrId=txt_bet, text=f"${_bet}",fill="#FD0000")
        
        _show = True               
    
BGM = _music(f"{Final_PIT_Location}//assets//BGM.wav",0)

#======================================================================#

#Lady
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    108.0,
    547.0,
    image=image_image_1
)

        
#blank_image
image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    349.0,
    525.0,
    image=image_image_2
)

canvas.create_rectangle(
    257.0,
    132.0,
    450.0,
    202.5,
    fill="#2C2C2C",
    outline="")

#status
txt_status = canvas.create_text(
    270.0,
    140.0,
    anchor="nw",
    text="",
    fill="#FFFFFF",
    font=("Orbitron Bold", 18 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    545.0,
    281.0,
    image=image_image_3
)

#bet
txt_bet = canvas.create_text(
    462.0,
    267.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Orbitron Bold", 24 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    162.0,
    283.0,
    image=image_image_4
)

#money
txt_money = canvas.create_text(
    79.0,
    267.0,
    anchor="nw",
    text="10000",
    fill="#FFFFFF",
    font=("Orbitron Bold", 24 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    569.0,
    163.0,
    image=image_image_5
)

#guess
txt_guess = canvas.create_text(
    530.0,
    104.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Orbitron Bold", 96 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    141.0,
    163.0,
    image=image_image_6
)

#number need to guess
txt_toGuess = canvas.create_text(
    107.0,
    104.0,
    anchor="nw",
    text="?",
    fill="#FFFFFF",
    font=("Orbitron Bold", 96 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    349.0,
    31.0,
    image=image_image_7
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: exit(),
    relief="flat"
)
button_1.place(
    x=668.0,
    y=8.0,
    width=25.0,
    height=24.0
)

#Enter
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: enter_button(),
    relief="flat"
)
button_2.place(
    x=261.0,
    y=616.9149169921875,
    width=115.0,
    height=43.085105895996094
)

#remover
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: remove_button(),
    relief="flat"
)
button_3.place(
    x=399.0,
    y=617.0,
    width=50.0,
    height=43.0
)

#======================================================================#

#chip_$50
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: bet_button(50),
    relief="flat"
)
button_4.place(
    x=588.0,
    y=498.0,
    width=45.0,
    height=45.0
)

#chip_$10
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: bet_button(10),
    relief="flat"
)
button_5.place(
    x=588.0,
    y=435.0,
    width=45.0,
    height=45.0
)

#chip_$5
button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: bet_button(5),
    relief="flat"
)
button_6.place(
    x=518.0,
    y=435.0,
    width=45.0,
    height=45.0
)
#chip_$5000
button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: bet_button(5000),
    relief="flat"
)
button_7.place(
    x=588.0,
    y=566.0,
    width=45.0,
    height=45.0
)

#chip_$1000
button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: bet_button(1000),
    relief="flat"
)
button_8.place(
    x=518.0,
    y=566.0,
    width=45.0,
    height=45.0
)

#chip_$100
button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: bet_button(100),
    relief="flat"
)
button_9.place(
    x=518.0,
    y=498.0,
    width=45.0,
    height=45.0
)

#======================================================================#


#Guess button number 9
button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(9),
    relief="flat"
)
button_10.place(
    x=401.0,
    y=555.0,
    width=45.0,
    height=45.0
)

#Guess button number 8
button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(8),
    relief="flat"
)
button_11.place(
    x=331.0,
    y=555.0,
    width=45.0,
    height=45.0
)

#Guess button number 7
button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(7),
    relief="flat"
)
button_12.place(
    x=261.0,
    y=555.0,
    width=45.0,
    height=46.0
)

#Guess button number 6
button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(6),
    relief="flat"
)
button_13.place(
    x=401.0,
    y=480.0,
    width=45.0,
    height=45.0
)

#Guess button number 5
button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(5),
    relief="flat"
)
button_14.place(
    x=331.0,
    y=480.0,
    width=45.0,
    height=45.0
)

#Guess button number 4
button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(4),
    relief="flat"
)
button_15.place(
    x=261.0,
    y=478.0,
    width=45.0,
    height=47.0
)

#Guess button number 3
button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(3),
    relief="flat"
)
button_16.place(
    x=401.0,
    y=405.0,
    width=45.0,
    height=45.0
)

#Guess button number 2
button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(2),
    relief="flat"
)
button_17.place(
    x=331.0,
    y=405.0,
    width=45.0,
    height=45.0
)

#Guess button number 1
button_image_18 = PhotoImage(
    file=relative_to_assets("button_18.png"))
button_18 = Button(
    image=button_image_18,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guess_button(1),
    relief="flat"
)
button_18.place(
    x=261.0,
    y=403.0,
    width=45.0,
    height=47.0
)


#======================================================================#

window.resizable(False, False)

window.mainloop()
